"""Where uploaded video bytes live.

`Storage` is the seam an S3-compatible backend will slot into later, so the
interface is deliberately object-store shaped: an opaque key, a byte stream, no
notion of directories or of a path the caller can choose.

The local implementation treats every key as hostile. Keys are generated by
`new_storage_key`, never derived from the uploaded filename, and
`LocalFileStorage` still re-validates each one before touching the filesystem,
because a key read back out of the database has been outside this process.
"""

import os
import re
import shutil
import uuid
from collections.abc import Iterable, Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import BinaryIO, Protocol

#: A key is one flat path component: hex, a dot, a lowercase extension.
STORAGE_KEY_PATTERN = re.compile(r"\A[0-9a-f]{32}\.[a-z0-9]{1,8}\Z")

CHUNK_BYTES = 1024 * 1024
_DIR_MODE = 0o700
_FILE_MODE = 0o600


class StorageError(Exception):
    """A storage operation could not be completed."""


class InvalidStorageKey(StorageError):
    """A key is not one this storage would ever have generated."""


class ObjectTooLarge(StorageError):
    """The incoming stream exceeded the caller's byte limit and was discarded."""


class ObjectNotFound(StorageError):
    """No object is stored under this key."""


def new_storage_key(extension: str) -> str:
    """A fresh, unguessable key for a new object.

    Random rather than derived from the video's public id: if a bucket is ever
    misconfigured or a URL signed carelessly, knowing an API identifier should
    not be enough to name the file.
    """
    suffix = extension.lower().lstrip(".")
    key = f"{uuid.uuid4().hex}.{suffix}"
    if not STORAGE_KEY_PATTERN.fullmatch(key):
        raise InvalidStorageKey(f"extension {extension!r} does not make a usable key")
    return key


class Storage(Protocol):
    """An object store keyed by opaque strings."""

    def write(self, key: str, chunks: Iterable[bytes], *, max_bytes: int) -> int:
        """Store `chunks` under `key` and return the byte count.

        Raises `ObjectTooLarge` if the stream exceeds `max_bytes`, and
        `FileExistsError` if the key is taken; in either case, and on any other
        failure, nothing is left behind under `key`.
        """

    def open(self, key: str) -> BinaryIO:
        """Open the stored object for reading. Raises `ObjectNotFound`."""

    def delete(self, key: str) -> None:
        """Remove the object. Succeeds whether or not it existed."""

    def exists(self, key: str) -> bool: ...

    def size(self, key: str) -> int:
        """Bytes currently stored under `key`. Raises `ObjectNotFound`."""

    def free_bytes(self) -> int | None:
        """Space left for new objects, or None when the question is meaningless.

        A laptop runs out of disk; S3 does not. Returning None is how a store
        says "do not ask", which keeps the caller free of a capability check.
        """


class LocalFileStorage:
    """Files in one directory on the local disk, for development.

    Writes go to a `.part` file that is renamed into place only once the whole
    stream has arrived, so an interrupted upload never leaves a truncated file
    that looks complete.
    """

    def __init__(self, root: Path) -> None:
        root.mkdir(parents=True, exist_ok=True, mode=_DIR_MODE)
        self.root = root.resolve(strict=True)

    def path_for(self, key: str) -> Path:
        """The file a key names, proven to be inside the storage root.

        `Path(root) / key` is not enough on its own: an absolute key replaces
        the root entirely, and `..` is only collapsed by resolution. The key
        pattern rules both out, and the containment check is the second fence in
        case the pattern is ever loosened.
        """
        if not STORAGE_KEY_PATTERN.fullmatch(key):
            raise InvalidStorageKey(f"not a storage key: {key!r}")
        path = (self.root / key).resolve()
        if not path.is_relative_to(self.root):
            raise InvalidStorageKey("storage key escapes the storage root")
        return path

    def write(self, key: str, chunks: Iterable[bytes], *, max_bytes: int) -> int:
        path = self.path_for(key)
        if path.exists():
            # Keys are random, so this means a bug rather than a collision --
            # and overwriting someone's match video is not the way to find out.
            raise FileExistsError(key)
        partial = path.with_name(f"{path.name}.part")
        written = 0
        try:
            # O_EXCL: never clobber an existing object. O_NOFOLLOW: never follow
            # a symlink someone planted at the destination.
            flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW
            with os.fdopen(os.open(partial, flags, _FILE_MODE), "wb") as out:
                for chunk in chunks:
                    written += len(chunk)
                    if written > max_bytes:
                        raise ObjectTooLarge(f"stream exceeded {max_bytes} bytes")
                    out.write(chunk)
            os.replace(partial, path)
        except BaseException:
            partial.unlink(missing_ok=True)
            raise
        return written

    def open(self, key: str) -> BinaryIO:
        path = self.path_for(key)
        try:
            return path.open("rb")
        except FileNotFoundError as exc:
            raise ObjectNotFound(key) from exc

    def delete(self, key: str) -> None:
        self.path_for(key).unlink(missing_ok=True)

    def exists(self, key: str) -> bool:
        return self.path_for(key).is_file()

    def size(self, key: str) -> int:
        path = self.path_for(key)
        try:
            return path.stat().st_size
        except FileNotFoundError as exc:
            raise ObjectNotFound(key) from exc

    def free_bytes(self) -> int | None:
        """Space left on the filesystem holding the store."""
        return shutil.disk_usage(self.root).free


@contextmanager
def discard_on_error(storage: Storage, key: str) -> Iterator[None]:
    """Delete `key` if the block fails.

    The upload writes the file before the database rows exist, so a failed
    insert would otherwise leave an object nothing refers to.
    """
    try:
        yield
    except BaseException:
        storage.delete(key)
        raise
